# Generated by Django 4.2.17 on 2024-12-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_predictionresult_delete_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionresult',
            old_name='predicted_label',
            new_name='label',
        ),
    ]
