# Generated by Django 4.2.17 on 2024-12-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_predicted_label_predictionresult_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionresult',
            old_name='label',
            new_name='predicted_label',
        ),
    ]
