# Generated by Django 4.2.17 on 2024-12-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_label_predictionresult_predicted_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionresult',
            old_name='predicted_label',
            new_name='label',
        ),
    ]
