# Generated by Django 4.2.17 on 2024-12-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_predicted_label_predictionresult_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='created_at',
        ),
    ]
